import pandas as pd
import re

# Read the Excel file
input_file = 'input_data/locations.xlsx'
df = pd.read_excel(input_file)

# Define a function to clean the city name
def clean_city_name(city_name):
    # Check if the city_name is not a string, and if so, convert it to an empty string
    if not isinstance(city_name, str):
        city_name = ''
    
    # List of country names to remove from city names
    countries = [
    'Greater',
    'Metropolitan',
    'Area',
    'Region',
    'City of ',
    'Afghanistan',  
    'Albania', 
    'Algeria', 
    'Andorra', 
    'Angola', 
    'Antigua and Barbuda', 
    'Antigua', 
    'Barbuda', 
    'Argentina', 
    'Armenia', 
    'Australia', 
    'Austria', 
    'Azerbaijan', 
    'Bahamas', 
    'Bahrain', 
    'Bangladesh', 
    'Barbados', 
    'Belarus', 
    'Belgium', 
    'Belize', 
    'Benin', 
    'Bhutan', 
    'Bolivia', 
    'Bosnia and Herzegovina', 
    'Bosnia', 
    'Herzegovina', 
    'Botswana', 
    'Brazil', 
    'Brunei', 
    'Bulgaria', 
    'Burkina Faso', 
    'Burundi', 
    'Côte d Ivoire', 
    'Cabo Verde', 
    'Cambodia', 
    'Cameroon', 
    'Canada', 
    'Central African Republic', 
    'Chad', 
    'Chile', 
    'China', 
    'Colombia', 
    'Comoros', 
    'Congo', 
    'Congo (Congo-Brazzaville)', 
    'Costa Rica', 
    'Croatia', 
    'Cuba', 
    'Cyprus', 
    'Czech Republic', 
    'Czechia', 
    'Democratic Republic of the Congo', 
    'Denmark', 
    'Djibouti', 
    'Dominica', 
    'Dominican Republic', 
    'Ecuador', 
    'Egypt', 
    'El Salvador', 
    'Equatorial Guinea', 
    'Eritrea', 
    'Estonia', 
    'Swaziland', 
    'Eswatini', 
    'Ethiopia', 
    'Fiji', 
    'Finland', 
    'France', 
    'Gabon', 
    'Gambia', 
    'Georgia', 
    'Germany', 
    'Ghana', 
    'Greece', 
    'Grenada', 
    'Guatemala', 
    'Guinea', 
    'Guinea-Bissau', 
    'Guyana', 
    'Haiti', 
    'Holy See', 
    'Honduras', 
    'Hungary', 
    'Iceland', 
    'India', 
    'Indonesia', 
    'Iran', 
    'Iraq', 
    'Ireland', 
    'Israel', 
    'Italy', 
    'Jamaica', 
    'Japan', 
    'Jordan', 
    'Kazakhstan', 
    'Kenya', 
    'Kiribati', 
    'Kuwait', 
    'Kyrgyzstan', 
    'Laos', 
    'Latvia', 
    'Lebanon', 
    'Lesotho', 
    'Liberia', 
    'Libya', 
    'Liechtenstein', 
    'Lithuania', 
    'Luxembourg', 
    'Madagascar', 
    'Malawi', 
    'Malaysia', 
    'Maldives', 
    'Mali', 
    'Malta', 
    'Marshall Islands', 
    'Mauritania', 
    'Mauritius', 
    'Mexico', 
    'Micronesia', 
    'Moldova', 
    'Monaco', 
    'Mongolia', 
    'Montenegro', 
    'Morocco', 
    'Mozambique', 
    'Myanmar', 
    'Namibia', 
    'Nauru', 
    'Nepal', 
    'Netherlands', 
    'New Zealand', 
    'Nicaragua', 
    'Niger', 
    'Nigeria', 
    'North Korea', 
    'North Macedonia', 
    'Norway', 
    'Oman', 
    'Pakistan', 
    'Palau', 
    'Palestine State', 
    'Panama', 
    'Papua New Guinea', 
    'Paraguay', 
    'Peru', 
    'Philippines', 
    'Poland', 
    'Portugal', 
    'Qatar', 
    'Romania', 
    'Russia', 
    'Rwanda', 
    'Saint Kitts and Nevis', 
    'Saint Lucia', 
    'Saint Vincent and the Grenadines', 
    'Samoa', 
    'San Marino', 
    'Sao Tome and Principe', 
    'Saudi Arabia', 
    'Senegal', 
    'Serbia', 
    'Seychelles', 
    'Sierra Leone', 
    'Singapore', 
    'Slovakia', 
    'Slovenia', 
    'Solomon Islands', 
    'Somalia', 
    'South Africa', 
    'South Korea', 
    'South Sudan', 
    'Spain', 
    'Sri Lanka', 
    'Sudan', 
    'Suriname', 
    'Sweden', 
    'Switzerland', 
    'Syria', 
    'Tajikistan', 
    'Tanzania', 
    'Thailand', 
    'Timor-Leste', 
    'Togo', 
    'Tonga', 
    'Trinidad and Tobago', 
    'Tunisia', 
    'Turkey', 
    'Turkmenistan', 
    'Tuvalu', 
    'Uganda', 
    'Ukraine', 
    'United Arab Emirates', 
    ' United Kingdom', 
    ' United States', 
    'United States of America', 
    'Uruguay', 
    'Uzbekistan', 
    'Vanuatu', 
    'Venezuela', 
    'Vietnam', 
    'Yemen', 
    'Zambia', 
    'Zimbabwe'
]

    # Remove the country names from the city name
    for country in countries:
        # Check if the city name is 'Mexico City' and the current country is 'Mexico'
        if city_name == 'Mexico City' and country == 'Mexico':
            continue
        city_name = city_name.replace(country, '')

    # Remove extra spaces
    cleaned_city_name = ' '.join(city_name.split())

    return cleaned_city_name

# Apply the clean_city_name function to the 'location' column
df['location2'] = df['location2'].apply(clean_city_name)

# Save the cleaned DataFrame to a new Excel file
output_file = 'input_data/input_cleanup_locations.xlsx'
df.to_excel(output_file, index=False)